# Generated by Django 4.0.4 on 2022-04-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
