# Generated by Django 4.0.4 on 2022-04-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_author_email_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='static/profile_pics'),
        ),
    ]
